window.APP_CONFIG = {
  email: "thuongnt.ce191329@gmail.com",

  socialLinks: [
    {
      label: "LinkedIn",
      url: "https://www.linkedin.com/in/nguyentienthuong-dev/",
      icon: "fab fa-linkedin-in",
    },
    {
      label: "GitHub",
      url: "https://github.com/Thuong404-lab",
      icon: "fab fa-github",
    },
  ],

  projects: [
    {
      title: "Library Management Web",
      image: "image/project-library-management.jpg",
      alt: "Library Management Web",
      url: null,
      source: "https://github.com/Thuong404-lab/Group_2_Library_Management_WEB",
      caseStudy: "case-study.html?project=library",
      tech: ["Java 17", "Spring Boot", "Spring Security", "SQL Server"],
      tags: ["java", "backend"],
      featured: true,
      problem: "Manage library accounts, inventory, borrowing, returns, fines, payments, and reports in one system.",
      role: "Academic team project",
      features: "Role-based access, reservations, PayOS payments, notifications, PDF reports.",
      lesson: "Applied Spring MVC, layered architecture, security, JPA, and third-party integrations.",
    },
    {
      title: "Photobooth Xi Đa",
      image: "image/photobooth.png",
      alt: "Photobooth",
      url: "https://photobooth-theta-cyan.vercel.app/",
      tech: ["HTML", "CSS", "JavaScript"],
      tags: ["html-css", "javascript"],
      featured: true,
      source: "https://github.com/Thuong404-lab/photobooth",
      problem: "Provide a private, browser-based way to capture and personalize photo strips.",
      role: "Developer",
      features: "Camera capture, layouts, filters, stickers, downloads, and video recap.",
      lesson: "Improved media handling, browser APIs, UI state, and responsive interactions.",
    },
    {
      title: "Smart Anti-Theft Camera",
      image: "image/project-smart-camera.jpg",
      alt: "Smart Anti-Theft Camera",
      url: null,
      source: "https://github.com/Thuong404-lab/Smart-Anti-Theft-Camera",
      tech: ["ESP32-CAM", "C++", "PIR Sensor", "IoT"],
      tags: ["iot"],
      featured: true,
      problem: "Detect suspicious movement and provide immediate local alerts with visual evidence.",
      role: "Developer",
      features: "Motion detection, camera capture, buzzer, LED, and intrusion alerts.",
      lesson: "Combined hardware sensors, embedded logic, and real-time event handling.",
    },
    {
      title: "Tạo QR",
      image: "image/taoqr.png",
      alt: "Tạo QR",
      url: "https://thuongnt-ktpm.github.io/taoqr/",
      tech: ["HTML", "CSS", "JavaScript"],
      tags: ["html-css", "javascript"],
      problem: "Generate QR codes quickly from user-provided content.", role: "Developer",
      features: "Instant generation, download, and responsive interface.", lesson: "Practiced API integration, validation, and compact UX design.",
    },
    {
      title: "Cảm ơn vì đã đến bên tôi",
      image: "image/image.png",
      alt: "Cảm ơn vì đã đến bên tôi",
      url: "https://thuongnt-ktpm.github.io/tienthuongchu/",
      tech: ["HTML", "CSS", "JavaScript"],
      tags: ["html-css", "javascript"],
      problem: "Create an emotional, story-driven web experience.", role: "Developer",
      features: "Interactive scenes, animation, audio, and responsive presentation.", lesson: "Practiced animation timing and experience-focused frontend design.",
    },
    {
      title: "Mưa Chữ",
      image: "image/muachu.png",
      alt: "Mưa Chữ",
      url: "https://thuongnt-ktpm.github.io/thuongkv/",
      tech: ["HTML", "CSS", "JavaScript"],
      tags: ["html-css", "javascript"],
      problem: "Turn typography into an interactive visual experience.", role: "Developer",
      features: "Animated text effects and browser-based interaction.", lesson: "Explored DOM animation, timing, and visual performance.",
    },
    {
      title: "TasksManager",
      image: "image/project-tasks-manager.jpg",
      alt: "TasksManager",
      url: null,
      source: "https://github.com/Thuong404-lab/TasksManager",
      caseStudy: "case-study.html?project=tasks",
      tech: ["Java 11", "Jakarta EE", "Hibernate", "SQL Server"],
      tags: ["java", "backend"],
      problem: "Organize and manage tasks through a structured Java web application.",
      role: "Developer",
      features: "Task workflows, persistent storage, JSP/JSTL views, and ORM mapping.",
      lesson: "Applied Jakarta EE, Hibernate/JPA, Maven, and layered web development.",
    },
  ],

};
